name: "showyourwork-action"
author: "Rodrigo Luger"
description: "Build reproducible scientific articles"
runs-on: ubuntu-latest
runs:
  using: "node12"
  main: "src/index.js"
inputs:
  conda-cache-number:
    description: "Bump this number to reset the conda cache"
    required: false
    default: "0"
  article-cache-number:
    description: "Bump this number to reset the article cache"
    required: false
    default: "0"
  output-branch-suffix:
    description: "Force-push output to branch with this suffix"
    required: false
    default: pdf
  github-token:
    description: "A token for access to GitHub (e.g. 'secrets.GITHUB_TOKEN')"
    required: false
    default: ${{ github.token }}
  build-tarball:
    description: "Build a tarball for easy ArXiV submission?"
    required: false
    default: true
  build-diff-on-pull-request:
    description: "Build the `latexdiff` version of a PDF on pull requests"
    required: false
    default: true
  latexdiff-url:
    description: "URL to download `latexdiff`"
    required: false
    default: "https://raw.githubusercontent.com/ftilmann/latexdiff/1.3.2/latexdiff"
  latexdiff-options:
    description: "Options passed to `latexdiff`"
    required: false
    default: "-t CFONT"
  latexpand-url:
    description: "URL to download `latexpand`"
    required: false
    default: "https://gitlab.com/latexpand/latexpand/-/raw/master/latexpand"
  showyourwork-version:
    description: "Version of `showyourwork` to use"
    required: false
    default: "latest"
  showyourwork-fork:
    description: "The URL of a fork of the `showyourwork` repo"
    required: false
  showyourwork-ref:
    description: "The name of a specific branch, tag, or commit on the fork of the `showyourwork` repo specified by `showyourwork-fork`"
    required: false
branding:
  icon: "book-open"
  color: "red"
